<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/second_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np


x = tf.constant([[11., 21., 31.],
                 [41., 51., 61.]])
y = np.array([[11., 21., 31.],
                 [41., 51., 61.]])

print(x)
print(y)

print(x.shape)
print(y.shape)

print(x.dtype)
print(y.dtype)

tf.Tensor(
[[11. 21. 31.]
 [41. 51. 61.]], shape=(2, 3), dtype=float32)
[[11. 21. 31.]
 [41. 51. 61.]]
(2, 3)
(2, 3)
<dtype: 'float32'>
float64
