<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/slice_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf


# Creating a 2D our_tensor of 10 rows and 5 columns
our_matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20],
          [21,22,23,24,25], 
          [26,27,28,29,30],
          [31,32,33,34,35],
          [36,37,38,39,40],
          [41,42,43,44,45],
          [46,47,48,49,50]]

our_tensor = tf.Variable(our_matrix, dtype=tf.int32) 
print(tf.rank(our_tensor))
print(our_tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(10, 5)


In [6]:
# we can select different rows and columns from the above our_tensor

first_row_fourth_element = our_tensor[0, 3]  # selecting the 4th element from the 1st row
print(f'First row, fourth element: {first_row_fourth_element}')  # -> 4

second_row = our_tensor[2]  # selecting the second row
print(f'Second row: {second_row}')

second_column = our_tensor[:, 1]  # selects the second column
print(f'Second column: {second_column}')

eleminating_one_row_and_then_eliminate_three_rows_in_succession = our_tensor[1::4]  # 
print(f'Eleminating one row and then three rows in succession: {eleminating_one_row_and_then_eliminate_three_rows_in_succession}')

eleminating_two_rows_and_then_eliminate_five_rows_in_succession = our_tensor[2::5]  # 
print(f'Eleminating two rows and then five rows in succession: {eleminating_two_rows_and_then_eliminate_five_rows_in_succession}')

second_column_in_row_one_and_four = our_tensor[0:5, 1]
print(f'Values from the first row to the fifth row belonging to the second column: {second_column_in_row_one_and_four}')

First row, fourth element: 4
Second row: [11 12 13 14 15]
Second column: [ 2  7 12 17 22 27 32 37 42 47]
Eleminating one row and then three rows in succession: [[ 6  7  8  9 10]
 [26 27 28 29 30]
 [46 47 48 49 50]]
Eleminating two rows and then five rows in succession: [[11 12 13 14 15]
 [36 37 38 39 40]]
Values from the first row to the fifth row belonging to the second column: [ 2  7 12 17 22]
