<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/slice_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

tensor_zero = tf.zeros([1,2,3])
print(tensor_zero)


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)


In [6]:
tensor_reshape_one = tf.reshape(tensor_zero, [3, 1, 2])
print(tensor_reshape_one)

tf.Tensor(
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]], shape=(3, 1, 2), dtype=float32)


In [7]:
tensor_reshape_two = tf.reshape(tensor_zero, [3, 2, 1])
print(tensor_reshape_two)

tf.Tensor(
[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]], shape=(3, 2, 1), dtype=float32)


In [8]:
tensor_reshape_three = tf.reshape(tensor_zero, [1, 3, 2])
print(tensor_reshape_three)

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(1, 3, 2), dtype=float32)


In [9]:
tensor_reshape_four = tf.reshape(tensor_zero, [2, 1, 3])
print(tensor_reshape_four)

tf.Tensor(
[[[0. 0. 0.]]

 [[0. 0. 0.]]], shape=(2, 1, 3), dtype=float32)


In [10]:
tensor_reshape_five = tf.reshape(tensor_zero, [2, 3, 1])
print(tensor_reshape_five)

tf.Tensor(
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]], shape=(2, 3, 1), dtype=float32)


# We have tested all types of combinations
### for all types of beginner friendly tensors examples please visit [My Blog on TensorFlow](https://sinhasanjib.com)