<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_dot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

X = tf.constant([[1, 2, 3], [4, 5, 6]])

Y = tf.constant([[1, 2], [3, 4], [5, 6]])

X, Y


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [10]:
X @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [15]:
#tf.tensordot(tf.transpose(X), Y, axes=1)

tf.tensordot(tf.transpose(Y), X, axes=0)

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 3,  6,  9],
         [12, 15, 18]],

        [[ 5, 10, 15],
         [20, 25, 30]]],


       [[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 4,  8, 12],
         [16, 20, 24]],

        [[ 6, 12, 18],
         [24, 30, 36]]]], dtype=int32)>

In [18]:
tf.matmul(X, tf.reshape(Y, (3, 2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [19]:
tf.matmul(Y, tf.reshape(X, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>