<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_shuffle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

not_shuffled_one = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# We will get different results each time
tf.random.shuffle(not_shuffled_one)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [3]:
not_shuffled_two = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# We will get different results each time
tf.random.shuffle(not_shuffled_two)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [13]:
# let's pass the seed parameter
tf.random.shuffle(not_shuffled_two, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [12]:
random_example_one = tf.random.Generator.from_seed(42) 
random_example_one = random_example_one.normal(shape=(3, 2)) 
random_example_two = tf.random.Generator.from_seed(42)
random_example_two = random_example_two.normal(shape=(3, 2))

random_example_one, random_example_two, random_example_one == random_example_two

# each time they will reproduce the same values

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled_one, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [18]:
tf.random.shuffle(not_shuffled_two, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>