<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/first-disorder/tensor_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf

<module 'tensorflow' from '/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py'>

In [4]:
# Create a rank 5 tensor (5 dimensions)
rank_five_tensor = tf.zeros([2, 3, 4, 5, 6])
rank_five_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [5]:
rank_five_tensor.shape, rank_five_tensor.ndim, tf.size(rank_five_tensor)

(TensorShape([2, 3, 4, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=720>)

In [6]:
# Getting various attributes of the tensor
print("Datatype of each element:", rank_five_tensor.dtype)
print("Number of dimensions which is known as rank:", rank_five_tensor.ndim)
print("The Shape of tensor:", rank_five_tensor.shape)
print("Elements along axis 0 of the tensor:", rank_five_tensor.shape[0])
print("Elements along last axis of the tensor:", rank_five_tensor.shape[-1])
print("Total number of elements (2*3*4*5*6):", tf.size(rank_five_tensor).numpy()) # .numpy() method converts to NumPy array

Datatype of each element: <dtype: 'float32'>
Number of dimensions which is known as rank: 5
The Shape of tensor: (2, 3, 4, 5, 6)
Elements along axis 0 of the tensor: 2
Elements along last axis of the tensor: 6
Total number of elements (2*3*4*5*6): 720


In [7]:
# Get the first 1 item of each dimension
rank_five_tensor[:1, :1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1, 1), dtype=float32, numpy=array([[[[[0.]]]]], dtype=float32)>

In [9]:
rank_five_tensor[:, :1, :1, :1]
# getting the dimension from each index except for the first one

<tf.Tensor: shape=(2, 1, 1, 1, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>