<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_data_change.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


# Creating a new tensor with default datatype (float32)
A = tf.constant([1.75, 85.44])

# Creating a new tensor with default datatype (int32)
B = tf.constant([128, 777])
A, B

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.75, 85.44], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([128, 777], dtype=int32)>)

In [2]:
# Changing from float32 to float16 so that we can reduce precision
A = tf.cast(A, dtype=tf.float16)
A

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.75, 85.44], dtype=float16)>

In [3]:
# Change from int32 to float32
B = tf.cast(B, dtype=tf.float32)
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([128., 777.], dtype=float32)>