<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensorflow_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf


x = tf.constant([[11., 21., 31.],
                 [41., 51., 61.]])


print(x)
print(f'Addition of two TensorFlow: {x + x}')
print(f'Subtraction of two TensorFlow: {x + x}')
print(f'Multiplication of a Tensor with a scalar: {2 * x}')
print(f'Division of a Tensor by a scalar: {x / 2}')
print(f'Multiplication of two TensorFlow: {x @ tf.transpose(x)}')

print(x.shape)

print(x.dtype)

tf.Tensor(
[[11. 21. 31.]
 [41. 51. 61.]], shape=(2, 3), dtype=float32)
Addition of two TensorFlow: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Subtraction of two TensorFlow: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of a Tensor with a scalar: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Division of a Tensor by a scalar: [[ 5.5 10.5 15.5]
 [20.5 25.5 30.5]]
Multiplication of two TensorFlow: [[1523. 3413.]
 [3413. 8003.]]
(2, 3)
<dtype: 'float32'>
