<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Import TensorFlow
import tensorflow as tf

tensor = tf.constant([[2, 5], [3, 8]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 8]], dtype=int32)>

In [5]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 50],
       [30, 79]], dtype=int32)>

In [6]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 50],
       [30, 79]], dtype=int32)>

In [7]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 50],
       [30, 79]], dtype=int32)>