<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

# we can add, subtract, multiply, or divide values to a tensor using the operators like +, -, * and /
tensor = tf.constant([[2, 3], [4, 5]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [4]:
tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-8, -7],
       [-6, -5]], dtype=int32)>

In [5]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [8]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [9]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [10]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-8, -7],
       [-6, -5]], dtype=int32)>

In [11]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.3],
       [0.4, 0.5]])>

In [7]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

# Original tensor remains unchanged

In [6]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.3],
       [0.4, 0.5]])>

In [ ]:
# Matrix manipulation depends on the same shape of tensors
