<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_constant_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf


tensor_that_can_be_changed = tf.Variable([5, 3])
tensor_that_can_be_changed


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 3], dtype=int32)>

In [13]:
tensor_that_can_not_be_changed = tf.constant([5, 3])
tensor_that_can_not_be_changed

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 3], dtype=int32)>

In [14]:
tensor_that_can_be_changed == tensor_that_can_not_be_changed

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [15]:
tensor_that_can_be_changed[0]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [16]:
tensor_that_can_be_changed[0].assign(3)
tensor_that_can_be_changed[0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tensor_that_can_not_be_changed[0].assign(3)

AttributeError: ignored

In [17]:
tensor_that_can_be_changed = tf.Variable([5, 3])
tensor_that_can_not_be_changed = tf.constant([15, 7])

tensor_that_can_be_changed == tensor_that_can_not_be_changed

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False, False])>