<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/first-disorder/tensor_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow.experimental.numpy as tnp
import timeit


tf.__version__

'2.8.2'

In [3]:
tnp.experimental_enable_numpy_behavior()

In [5]:
ones = tnp.ones([5, 3], dtype=tnp.int32)
ones

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [6]:
test = tnp.test([5, 3], dtype=tnp.int32)
test

AttributeError: ignored

In [10]:
print(ones.device)
print(ones.dtype)
print(ones.ndim)

/job:localhost/replica:0/task:0/device:CPU:0
<dtype: 'int32'>
2


In [11]:
x = tnp.ones([2, 3])
y = tnp.ones([3])
z = tnp.ones([1, 2, 1])

x, y, z

(<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>,
 <tf.Tensor: shape=(1, 2, 1), dtype=float64, numpy=
 array([[[1.],
         [1.]]])>)

In [12]:
isinstance(ones, tf.Tensor)

True