<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
import numpy as np


x = tf.constant([[11., 21., 31.],
                 [41., 51., 61.]])
y1 = np.array([[[1, 2],
        [3, 4]],
       [[5, 6],
        [7, 8]]])

y2 = np.array([['a', 'b'],
       ['c', 'd']], dtype=object)

print(x)
print(f'Addition of two TensorFlow: {x + x}')
print(f'Multiplication of a Tensor with a scalar: {2 * x}')
print(f'Multiplication of two TensorFlow: {x @ tf.transpose(x)}')

print(y)
print(f'Addition of two NumPy Tensors: {y + y}')
print(f'Multiplication of one NumPy Tensor with a scalar: {2 * y}')
print(f'Multiplication of two NumPy Tensors: {np.tensordot(y1, y2)}')

print(x.shape)
print(y.shape)

print(x.dtype)
print(y.dtype)

tf.Tensor(
[[11. 21. 31.]
 [41. 51. 61.]], shape=(2, 3), dtype=float32)
Addition of two TensorFlow: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of a Tensor with a scalar: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of two TensorFlow: [[1523. 3413.]
 [3413. 8003.]]
[[11. 21. 31.]
 [41. 51. 61.]]
Addition of two NumPy Tensors: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of one NumPy Tensor with a scalar: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of two NumPy Tensors: ['abbcccdddd' 'aaaaabbbbbbcccccccdddddddd']
(2, 3)
(2, 3)
<dtype: 'float32'>
float64
