<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_constant_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf


tensor_that_can_be_changed = tf.Variable([5, 3])
tensor_that_can_be_changed


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [4]:
tensor_that_can_not_be_changed = tf.constant([5, 3])
tensor_that_can_not_be_changed

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [5]:
tensor_that_can_be_changed == tensor_that_can_not_be_changed

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [8]:
tensor_that_can_be_changed[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [10]:
tensor_that_can_be_changed[0].assign(3)
tensor_that_can_be_changed[0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
tensor_that_can_not_be_changed[0].assign(3)

AttributeError: ignored