<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tf_mul_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

X = tf.constant([[1, 2, 3], [4, 5, 6]])
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [2]:
Y = tf.constant([[1, 2], [3, 4], [5, 6]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [3]:
# this will work
X @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [4]:
M = tf.constant([[1, 2, 3], [4, 5, 6]])
M

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [17]:
N = tf.constant([[7, 8, 9], [10, 11, 12]])
N

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [9]:
# this will not work
M @ N

InvalidArgumentError: ignored

In [22]:
M = tf.reshape(M, shape=(3, 2))

In [23]:
M

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [24]:
# this will work
M @ N

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>