<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/reshape_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tensor_zero = tf.zeros([1,2,3])
print(tensor_zero)


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)


In [ ]:
tensor_reshape_one = tf.reshape(tensor_zero, [3, 1, 2])
print(tensor_reshape_one)

tf.Tensor(
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]], shape=(3, 1, 2), dtype=float32)


In [ ]:
tensor_reshape_two = tf.reshape(tensor_zero, [3, 2, 1])
print(tensor_reshape_two)

tf.Tensor(
[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]], shape=(3, 2, 1), dtype=float32)


In [ ]:
tensor_reshape_three = tf.reshape(tensor_zero, [1, 3, 2])
print(tensor_reshape_three)

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(1, 3, 2), dtype=float32)


In [ ]:
tensor_reshape_four = tf.reshape(tensor_zero, [2, 1, 3])
print(tensor_reshape_four)

tf.Tensor(
[[[0. 0. 0.]]

 [[0. 0. 0.]]], shape=(2, 1, 3), dtype=float32)


In [ ]:
tensor_reshape_five = tf.reshape(tensor_zero, [2, 3, 1])
print(tensor_reshape_five)

tf.Tensor(
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]], shape=(2, 3, 1), dtype=float32)


In [18]:
tensor_reshape_six = tf.reshape(tensor_zero, [3, 2])
print(tensor_reshape_six)
tensor_reshape_seven = tf.reshape(tensor_zero, [2, 3])
print(tensor_reshape_seven)
tensor_reshape_eight = tf.reshape(tensor_zero, [2, -1])
print(tensor_reshape_eight)
tensor_reshape_nine = tf.reshape(tensor_zero, [3, -1]) # it will automatically adjust the shape
print(tensor_reshape_nine)
tensor_reshape_ten = tf.reshape(tensor_zero, [1, -1]) # it will automatically adjust the shape
print(tensor_reshape_ten)
tensor_reshape_eleven = tf.reshape(tensor_zero, [6, -1]) # it will automatically adjust the shape
print(tensor_reshape_eleven)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor([[0. 0. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(6, 1), dtype=float32)


the above shapes are also possible, since the product of elements are 6

# We have tested all types of combinations
### for all types of beginner friendly tensors examples please visit [My Blog on TensorFlow](https://sinhasanjib.com)