<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tf_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf  
print(tf.version)  

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
string = tf.Variable("Here a string", tf.string) 
number = tf.Variable(3244444444555, tf.int64)
floating = tf.Variable(456233.567845896123, tf.float64)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Here a string'>
<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=3244444444555>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=456233.56>


In [ ]:
rank_one_tensor = tf.Variable(["One Dimension"], tf.string) 
rank_two_tensor = tf.Variable([["Two Dimension", "Two Dimension"], ["Two Dimension", "Two Dimension"]], tf.string)

print(rank_one_tensor)
print(rank_two_tensor)

print(rank_one_tensor.shape) # shape: how many elements present
print(rank_two_tensor.shape)

rank_two = tf.ones([2, 3, 6])
tensor_two = tf.reshape(rank_two, [1, 3, 12])
print(tensor_two)
print(rank_one_tensor.shape)


<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'One Dimension'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Two Dimension', b'Two Dimension'],
       [b'Two Dimension', b'Two Dimension']], dtype=object)>
(1,)
(2, 2)
tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]], shape=(1, 3, 12), dtype=float32)
(1,)
