<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/tensor_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np


x = tf.constant([[11., 21., 31.],
                 [41., 51., 61.]])
y1 = np.array([[[1, 2],
        [3, 4]],
       [[5, 6],
        [7, 8]]])

y2 = np.array([['a', 'b'],
       ['c', 'd']], dtype=object)

print(x)
print(f'Addition of two TensorFlow: {x + x}')
print(f'Multiplication of a Tensor with a scalar: {2 * x}')
print(f'Multiplication of two TensorFlow: {x @ tf.transpose(x)}')

print(y1)
print(y2)

print(f'Multiplication of one NumPy Tensor with a scalar: {2 * y1}')
print(f'Multiplication of two NumPy Tensors: {np.tensordot(y1, y2)}')

print(x.shape)
print(y1.shape)
print(y2.shape)

print(x.dtype)
print(y1.dtype)
print(y2.dtype)

tf.Tensor(
[[11. 21. 31.]
 [41. 51. 61.]], shape=(2, 3), dtype=float32)
Addition of two TensorFlow: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of a Tensor with a scalar: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of two TensorFlow: [[1523. 3413.]
 [3413. 8003.]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[['a' 'b']
 ['c' 'd']]
Multiplication of one NumPy Tensor with a scalar: [[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]
Multiplication of two NumPy Tensors: ['abbcccdddd' 'aaaaabbbbbbcccccccdddddddd']
(2, 3)
(2, 2, 2)
(2, 2)
<dtype: 'float32'>
int64
object
