<a href="https://colab.research.google.com/github/sanjibsinha/tensorflow-for-beginners/blob/google-colabs/third_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np


x = tf.constant([[11., 21., 31.],
                 [41., 51., 61.]])
y = np.array([[11., 21., 31.],
                 [41., 51., 61.]])

print(x)
print(f'Addition of two TensorFlow: {x + x}')
print(f'Multiplication of two TensorFlow: {2 * x}')
print(y)
print(f'Addition of two NumPy Tensors: {y + y}')
print(f'Multiplication of two NumPy Tensors: {2 * y}')

print(x.shape)
print(y.shape)

print(x.dtype)
print(y.dtype)

tf.Tensor(
[[11. 21. 31.]
 [41. 51. 61.]], shape=(2, 3), dtype=float32)
Addition of two TensorFlow: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of two TensorFlow: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
[[11. 21. 31.]
 [41. 51. 61.]]
Addition of two NumPy Tensors: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
Multiplication of two NumPy Tensors: [[ 22.  42.  62.]
 [ 82. 102. 122.]]
(2, 3)
(2, 3)
<dtype: 'float32'>
float64
